# What version of Docker Compose are we going to use? Latest
version: "3.7"

# What volumes do we need?
volumes:
  db_data: {}
  wp_data: {}

# What networks do we need?
networks:
  default-net: {}

# What services do we need?
services:
  # MySQL Database https://hub.docker.com/_/mysql
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - default-net

  # WordPress https://hub.docker.com/_/wordpress
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html/
      - ./themes:/var/www/html/wp-content/themes/
      - ./plugins:/var/www/html/wp-content/plugins/
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    ports:
      - 8000:80
    networks:
      - default-net

  # PHPMyAdmin https://hub.docker.com/r/phpmyadmin/phpmyadmin/
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    ports:
      - 8001:80
    networks:
      - default-net
